name: Playwright Tests
on: 
  push: 
    branches: [ main ]
jobs: 
  playwrighttests: 
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/playwright:v1.37.1-jammy
      env: 
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Rus tests
       run: |
        echo "Start the shopping store application"
        ./shopping-store-linux-amd64 &
        echo "Install dependecies from the lockfile"
        npm ci
        echo "Run the tests"
        npm run test:ci